Repository labs-web/prototype, pull requests merged in 2024-02, with the labels that each got.

#30 contexte-projet
  docs/contexte-projet/contexte-projet.md
  docs/contexte-projet/images/prototype.png
Labels: en_validation

#51 prérequis
  docs/prérequis/images/prérequi.png
  docs/prérequis/prérequis.md
Labels: en_validation

#54 contexte-projet
  docs/contexte-projet/contexte-projet.md
  docs/contexte-projet/images/2tup.png
  docs/contexte-projet/images/analyse-technique.png
Labels: en_validation

#58 prérequis
  docs/prérequis/prérequis.md
Labels: en_validation

#64 contexte-projet
  docs/contexte-projet/contexte-projet.md
  docs/contexte-projet/images/design-thinking.png
Labels: en_validation

#72 compétences-cibles
  docs/Compétences-cibles/Competences.fig
  docs/Compétences-cibles/compétences-cibles.md
Labels: en_validation

#96 6-prérequis
  docs/prérequis/prérequis.md
Labels: en_validation

#98 20-diagramme-classes
  docs/diagramme-classes/diagramme-classes.md
  docs/diagramme-classes/images/diagramme-classes.png
Labels: terminé

#101 2-backlog
  backlog/exposé/2.exposé-name-space.15.md
  backlog/exposé/2.exposé-unit-test.16.md
  backlog/feature/1.init-lab.1.md
  backlog/feature/1.table-de-matière.25.md
  backlog/feature/10.projets_authorization.39.md
  backlog/feature/10.taches_authorization.77.md
  backlog/feature/10.utilisateurs_authorization.78.md
  backlog/feature/2.conclusion.79.md
  backlog/feature/20.multi-langue-à-supprimer.80.md
  backlog/feature/20.présentation-à-supprimer.34.md
  backlog/feature/20.présentation-à-supprimer.43.md
  backlog/feature/20.rapport-à-supprimer.44.md
  backlog/feature/3.Diagramme de packages.75.md
  backlog/feature/3.analyse.11.md
  backlog/feature/3.diagramme-classes.20.md
  backlog/feature/7.projets_unit-test.40.md
  backlog/feature/7.taches_unit-test.81.md
  backlog/feature/7.utilisateurs_unit-test.82.md
  backlog/feature/8.projets_frontend.83.md
  backlog/feature/8.taches_frontend.84.md
  backlog/feature/8.utilisateurs_frontend.85.md
  backlog/feature/9.authentification.38.md
Labels: en_validation

#100 75-diagramme-de-packages
  docs/Diagramme-de-packages/Diagramme-de-packages.fig
  docs/Diagramme-de-packages/Diagramme-de-packages.md
  docs/Diagramme-de-packages/images/Diagramme-des-packages.png
Labels: en_validation

#105 12-maquettes
  docs/maquettes/compte-rendu.md
  docs/maquettes/images/ajoute.png
  docs/maquettes/images/index.png
  docs/maquettes/images/login.png
  docs/maquettes/images/modifier.png
  docs/maquettes/images/more-detaills.png
  docs/maquettes/images/taches.png
  docs/maquettes/maquettes.md
  maquettes/Readme.md
  maquettes/compte-rendu.md
  maquettes/maquettes.md
  maquettes/package-lock.json
  maquettes/view/assets/css/app.css
  maquettes/view/assets/images/logo.png
  maquettes/view/assets/images/man.png
  maquettes/view/assets/js/app.js
  maquettes/view/layouts/aside.php
  maquettes/view/layouts/heade.php
  maquettes/view/layouts/nav.php
  maquettes/view/layouts/script-link.php
  maquettes/view/login/index.php
  maquettes/view/projets/create.php
  maquettes/view/projets/edit.php
  maquettes/view/projets/form.php
  maquettes/view/projets/index.php
  maquettes/view/projets/show.php
  maquettes/view/taches/ajouter.php
  maquettes/view/taches/edit.php
  maquettes/view/taches/form.php
  maquettes/view/taches/index.php
  maquettes/view/taches/show.php
  maquettes/view/utilisateurs/ajouter.php
  maquettes/view/utilisateurs/edit.php
  maquettes/view/utilisateurs/form.php
  maquettes/view/utilisateurs/index.php
  maquettes/view/utilisateurs/show.php
Labels: terminé

#111 15-exposé-name-space
  docs/Exposé-name-space/exposé-name-space.md
  docs/Exposé-name-space/images/Déclarer-un-namespace.png
  docs/Exposé-name-space/images/namespace.png
  docs/Exposé-name-space/présentation.md
  docs/Exposé-name-space/rapport.md
Labels: en_validation

#104 16-exposé-unit-test
  docs/exposé-unit-test/exposé-unit-test.md
  docs/exposé-unit-test/images/Database.jpg
  docs/exposé-unit-test/images/Resetting-database.png
  docs/exposé-unit-test/images/feature-unit-test-laravel.png
  docs/exposé-unit-test/images/uni_test-laravel.png
  docs/exposé-unit-test/images/unit_test.png
  docs/exposé-unit-test/presentation.md
  docs/exposé-unit-test/rapport.md
Labels: en_cours

#116 16-exposé-unit-test
  docs/exposé-unit-test/exposé-unit-test.md
  docs/exposé-unit-test/presentation.md
  docs/exposé-unit-test/rapport.md
Labels: en_validation

#117 10-init-app
  app/app/Providers/AppServiceProvider.php
  app/app/Repositories/AppBaseRepository.php
Labels: en_validation

#118 2-backlog
  backlog/feature/6.projets_backend.22.md
  backlog/feature/6.tasks-backend.42.md
  backlog/feature/6.utilisateurs-backend.41.md
  backlog/feature/7.projets_unit-test.40.md
  backlog/feature/7.taches_unit-test.81.md
  backlog/feature/7.utilisateurs_unit-test.82.md
  backlog/feature/8.projets_frontend.83.md
  backlog/feature/8.taches_frontend.84.md
  backlog/feature/8.utilisateurs_frontend.85.md
Labels: en_validation

#127 2-backlog
  backlog/feature/6.projets_backend.22.md
  backlog/feature/6.tasks-backend.42.md
  backlog/feature/6.utilisateurs-backend.41.md
  backlog/feature/7.projets_unit-test.40.md
  backlog/feature/7.taches_unit-test.81.md
  backlog/feature/7.utilisateurs_unit-test.82.md
  backlog/feature/8.utilisateurs_frontend.85.md
Labels: en_validation

#129 2-backlog
  backlog/feature/3.conception.md
  backlog/feature/6.projets_backend.22.md
  backlog/feature/6.tasks-backend.42.md
  backlog/feature/6.utilisateurs-backend.41.md
  backlog/feature/7.projets_unit-test.40.md
  backlog/feature/7.taches_unit-test.81.md
  backlog/feature/7.utilisateurs_unit-test.82.md
Labels: en_validation

#134 132-conception
  docs/conception/Diagramme-de-packages.fig
  docs/conception/conception.md
  docs/conception/images/Diagramme-des-packages.png
  docs/conception/images/diagramme-classes.png
Labels: en_validation

#136 131-conception
  docs/conception/conception.md
Labels: en_validation

#138 12-maquettes
  maquettes/view/layouts/script-link.php
  maquettes/view/projets/form.php
Labels: en_validation
